
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Directions = lazy(() => import("./pages/Directions.tsx"));
const Map = lazy(() => import("./pages/Map.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/directions", element: <Directions />},
	{ path: "/map", element: <Map />},
	{ path: "/profile", element: <Profile />},

];
